[package]
name = "dictionary-builder"
version = "0.1.0"
authors = ["Olivier ROLAND <newca12@users.noreply.github.com>"]
edition = "2018"

[dependencies]
config = "0.10.1"
serde_derive = "^1.0.8"
serde = "^1.0.8"
unicode-segmentation = "1.6.0"
flate2 = "1.0"
bzip2 = { git = "https://github.com/alexcrichton/bzip2-rs" }
parse_mediawiki_dump = "0.1.0"
