//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.11 at 10:32:53 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mediawiki.org/xml/export-0.3/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.edla.wikimediaschema;
