//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.06 at 10:30:10 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mediawiki.org/xml/export-0.3/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.edla.wikimediaschema;
