//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.17 at 05:29:25 PM CET 
//


package org.edla.wikimediaschema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ns" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="redirect" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="restrictions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="revision" type="{http://www.mediawiki.org/xml/export-0.6/}RevisionType"/>
 *           &lt;element name="upload" type="{http://www.mediawiki.org/xml/export-0.6/}UploadType"/>
 *           &lt;element name="logitem" type="{http://www.mediawiki.org/xml/export-0.6/}LogItemType"/>
 *         &lt;/choice>
 *         &lt;element name="discussionthreadinginfo" type="{http://www.mediawiki.org/xml/export-0.6/}DiscussionThreadingInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PageType", propOrder = {
    "title",
    "ns",
    "id",
    "redirect",
    "restrictions",
    "revisionOrUploadOrLogitem",
    "discussionthreadinginfo"
})
public class PageType {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ns;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;
    protected String redirect;
    protected String restrictions;
    @XmlElements({
        @XmlElement(name = "revision", type = RevisionType.class),
        @XmlElement(name = "upload", type = UploadType.class),
        @XmlElement(name = "logitem", type = LogItemType.class)
    })
    protected List<Object> revisionOrUploadOrLogitem;
    protected DiscussionThreadingInfo discussionthreadinginfo;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the ns property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNs() {
        return ns;
    }

    /**
     * Sets the value of the ns property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNs(BigInteger value) {
        this.ns = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the redirect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedirect() {
        return redirect;
    }

    /**
     * Sets the value of the redirect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedirect(String value) {
        this.redirect = value;
    }

    /**
     * Gets the value of the restrictions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestrictions() {
        return restrictions;
    }

    /**
     * Sets the value of the restrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestrictions(String value) {
        this.restrictions = value;
    }

    /**
     * Gets the value of the revisionOrUploadOrLogitem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the revisionOrUploadOrLogitem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRevisionOrUploadOrLogitem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RevisionType }
     * {@link UploadType }
     * {@link LogItemType }
     * 
     * 
     */
    public List<Object> getRevisionOrUploadOrLogitem() {
        if (revisionOrUploadOrLogitem == null) {
            revisionOrUploadOrLogitem = new ArrayList<Object>();
        }
        return this.revisionOrUploadOrLogitem;
    }

    /**
     * Gets the value of the discussionthreadinginfo property.
     * 
     * @return
     *     possible object is
     *     {@link DiscussionThreadingInfo }
     *     
     */
    public DiscussionThreadingInfo getDiscussionthreadinginfo() {
        return discussionthreadinginfo;
    }

    /**
     * Sets the value of the discussionthreadinginfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscussionThreadingInfo }
     *     
     */
    public void setDiscussionthreadinginfo(DiscussionThreadingInfo value) {
        this.discussionthreadinginfo = value;
    }

}
